<link href="/assets/openview/css/bootstrap.min.css" rel="stylesheet">
<link href="<?= $this->baseUrl() ?>/assets/admin/layout/css/custom.css" rel="stylesheet" type="text/css"/>
<link href="/assets/openview/css/styles.css?v=1.1" rel="stylesheet">
<link href="/assets/admin/pages/css/login-soft.css" rel="stylesheet">
<link href="/assets/global/plugins/jquery-ui/jquery-ui-1.10.3.custom.min.css" rel="stylesheet">
<link href="/assets_v2/global/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
<link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
<link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet"
      type="text/css">
<link rel="shortcut icon" href="<?= $this->baseUrl(); ?>/assets/frontend/logos/IsotipoMel.png">

<style>
    body {
        background: none;
    }

    .font-light {
        font-weight: 100 !important;
    }

    .font-14, .font-14 * {
        font-size: 14px !important;
        font-weight: 100 !important;
    }

    .font-12, .font-12 * {
        font-size: 12px !important;
        font-weight: 100 !important;
    }

    .font-11, .font-11 * {
        font-size: 11px !important;
        font-weight: 100 !important;
    }

    .textarea-content {
        white-space: pre-line;
    }

    .table {
        margin-bottom: 15px;
    }

    .table-cell {
        padding: 5px;
        /*hyphens: auto;*/
        min-height: 35px;
    }

    .table.color-coding-table {
        width: 100px;
    }

    .comment_holder {
        visibility: hidden;
    }

    .text-diff.text-diff-removed, .text-diff.text-diff-removed * {
        color: red !important;
        text-decoration: line-through !important;
    }

    .text-diff.text-diff-added, .text-diff.text-diff-added * {
        color: green !important;
    }
</style>
